/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


#define ADC_BASE_ADDR			0x40012000UL
#define ADC_CR1_REG_OFFSET		0x04UL
#define ADC_CR1_REG_ADDR		(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR			0x40023800UL
#define RCC_APB2_EN_OFFSET		0x44UL
#define RCC_APB2_EN				(RCC_BASE_ADDR + RCC_APB2_EN_OFFSET)


int main(void)
{
	uint32_t *pApb2EnReg = (uint32_t*) RCC_APB2_EN;
    uint32_t *pAdcCrlReg = (uint32_t*) ADC_CR1_REG_ADDR;


    *pApb2EnReg |= (1 << 8);
    *pAdcCrlReg |= (1 << 8);


	for(;;);
}
