/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


#define RCC_BASE_ADDR				0x40023800UL

#define RCC_CFGR_OFFSET				0x08UL

#define GPIOA_BASE_ADDR				0x40020000UL

#define RCC_AHB1_OFFSET				0x30UL


int main()
{

	uint32_t *pRccCrReg = 		(uint32_t*)RCC_BASE_ADDR;
	uint32_t *pRccCfgrReg = 	(uint32_t*)(RCC_BASE_ADDR + RCC_CFGR_OFFSET);
	uint32_t *pRccAhb1Reg = 	(uint32_t*)(RCC_BASE_ADDR + RCC_AHB1_OFFSET);
	uint32_t *pGpioaModerReg =	(uint32_t*)GPIOA_BASE_ADDR;

	//1. Enable the HSE clock using HSEON bit (RCC_CR)
	*pRccCrReg |= ( 1 << 16 );

	//2. Wait until HSE clock from the external stabilizes
	while( !(*pRccCrReg & ( 1 << 16 )) );

	//3. Switch the system clock to HSE (RCC_CFGR)
	*pRccCfgrReg &= ( 0 << 0);
	*pRccCfgrReg &= ( 0 << 1);

	*pRccCfgrReg &= ( 1 << 0);


	//4. Do MCO1 settings to measure it
	*pRccCfgrReg &= ( 0 << 21);
	*pRccCfgrReg &= ( 0 << 22);

	*pRccCfgrReg &= ( 1 << 22);


	*pRccAhb1Reg |= ( 1 << 0);


	*pGpioaModerReg |= ( 1 << 17 );



	for( ; ; );
}
